"""
Pulls the durable data out of the League History Database workbook.

    python scripts/history/import.py "C:/path/to/AFFL League History Database.xlsx"

Writes src/lib/history/archive.js, which /api/history merges under the live
ESPN data. Re-run it whenever the workbook is updated; nothing reads the
workbook at runtime.

Needs Python 3 and nothing else — an xlsx is a zip of XML, and xlsx.py reads it
with the standard library.

Most of its sheets are calculators — a filter cell at the top and formulas
underneath — so they hold no data of their own. What is actually recorded is the
game log, the titles, the divisions, the dues and the player weeks; everything
the workbook shows is computed from those, and so is the page.
"""
import json
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from xlsx import Workbook

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
SRC = sys.argv[1] if len(sys.argv) > 1 else os.path.join(ROOT, 'AFFL League History Database.xlsx')
OUT = os.path.join(ROOT, 'src', 'lib', 'history', 'archive.js')

if not os.path.exists(SRC):
    sys.exit(
        f'No workbook at {SRC}\n'
        'Usage: python scripts/history/import.py "path/to/AFFL League History Database.xlsx"'
    )

wb = Workbook(SRC)
sheets = {n: p for n, p, s in wb.sheets}
rows = lambda n: [r for r in wb.rows(sheets[n]) if any(c not in (None, '') for c in r)]


def num(v):
    if v is None or v == '':
        return None
    try:
        return round(float(v), 2)
    except (TypeError, ValueError):
        return None


# ---------- games ----------
# Columns: count, year, week, team1, score1, (blank), score2, team2, type, seed
games, placements = [], []
for r in rows('Game Log')[2:]:
    if not r or not r[1] or not isinstance(r[1], int):
        continue
    season, week = r[1], r[2]
    a, ap, bp, b, kind = r[3], num(r[4]), num(r[6]), r[7], r[8]
    if not a or not b:
        continue

    if kind == '-':
        # Not a game: a placement row carrying where a team finished.
        placements.append({'season': season, 'week': week, 'winner': a, 'loser': b,
                           'seed': r[9] if len(r) > 9 else None})
        continue

    games.append({'season': season, 'week': week, 'type': kind,
                  'a': a, 'ap': ap, 'b': b, 'bp': bp})

# ---------- titles ----------
titles = {}
for r in rows('League Titles')[2:]:
    if r and isinstance(r[0], int) and r[1]:
        titles.setdefault(r[0], {})['champion'] = r[1]
    if len(r) > 4 and isinstance(r[3], int) and r[4]:
        titles.setdefault(r[3], {})['sacko'] = r[4]
titles = [{'season': s, **v} for s, v in sorted(titles.items())]

# ---------- owners ----------
owners = []
for r in rows('All-Time Owners')[2:]:
    if r and r[0] and r[1] in ('ACTIVE', 'RETIRED'):
        owners.append({'name': r[0], 'status': r[1].title()})

# ---------- divisions ----------
divisions = []
for r in rows('Divisions')[1:]:
    if r and isinstance(r[0], int) and len(r) > 3 and r[1] and r[2]:
        divisions.append({'season': r[0], 'owner': r[1], 'division': r[2], 'finish': r[3]})

# ---------- dues ----------
finances = []
for r in rows('Financial')[2:]:
    if r and isinstance(r[0], int) and (r[1] or 0):
        finances.append({'season': r[0], 'buyIn': num(r[1]), 'weekly': num(r[2]),
                         'first': num(r[8]), 'second': num(r[9])})

# ---------- best player weeks ----------
# The list runs to 5,839 rows and only covers 2021-23; the tail is ordinary
# afternoons. The top of it is the part worth keeping.
players = []
for r in rows('Player List')[1:]:
    if r and r[0] and r[2] and num(r[3]) is not None:
        players.append({'season': r[0], 'week': r[1], 'player': r[2], 'score': num(r[3]),
                        'position': r[6], 'manager': r[8] if len(r) > 8 else None})
players.sort(key=lambda p: -p['score'])
players = [p for p in players if p['position'] not in ('Bench', 'IR')][:40]

data = {
    'source': 'AFFL League History Database',
    'seasons': sorted({g['season'] for g in games}),
    'titles': titles,
    'owners': owners,
    'divisions': divisions,
    'finances': finances,
    'topPlayers': players,
    'games': games,
    'placements': placements,
}

HEADER = """/**
 * The league's own record of 2021-2025, imported from the League History
 * Database workbook. Generated by scripts/history/import.py — do not edit.
 *
 * ESPN is the authority on scores and is read live, so this is here for what
 * ESPN cannot tell us: the sackos (its final rankings disagree every year), the
 * owner behind a team it has since forgotten, and the player weeks it would
 * take a request per week to rebuild.
 */

export default """

with open(OUT, 'w', encoding='utf-8') as f:
    f.write(HEADER)
    json.dump(data, f, separators=(',', ':'))
    f.write('\n')

print('games      ', len(games))
print('placements ', len(placements))
print('titles     ', len(titles))
print('owners     ', len(owners))
print('divisions  ', len(divisions))
print('finances   ', len(finances))
print('topPlayers ', len(players))
print('bytes      ', f'{os.path.getsize(OUT):,}')
print('written to ', OUT)
