#!/usr/bin/env node
/**
 * Precomputes trades and waiver pickups for completed seasons.
 *
 *   npm run trades:import
 *   npm run trades:import -- --seasons 2021,2022
 *
 * Both come out of one read. A season's roster movement costs one weekly roster
 * request per week — about a megabyte each, seventeen a season — because that
 * ownership timeline is the only thing that recovers the half of a trade ESPN's
 * end-of-season rosters have forgotten, and the only thing that can name a
 * waiver pickup at all. Completed seasons never change, so paying for them on
 * every cold request would be waste; this pays once and writes
 * src/lib/trades/archive.js and src/lib/waivers/archive.js, which /api/trades
 * and /api/waivers serve alongside a live read of the season being played.
 *
 * Re-run it when a season finishes. Both files are regenerated each time, so
 * running it twice is harmless.
 */

import { writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

import { loadDotEnv } from '../load-env.mjs'
import { assertConfigured, currentSeason, isValidSeason, readEspnEnv } from '../../src/lib/espn/config.js'
import { LEAGUE_VIEWS } from '../../src/lib/espn/endpoints.js'
import { fetchLeagueRaw } from '../../src/lib/espn/fetchLeague.js'
import { loadSeasonActivity } from '../../src/lib/season/activity.js'

loadDotEnv()

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..', '..')
const TRADES_OUT = join(ROOT, 'src', 'lib', 'trades', 'archive.js')
const WAIVERS_OUT = join(ROOT, 'src', 'lib', 'waivers', 'archive.js')

function arg(name) {
  const index = process.argv.indexOf(`--${name}`)
  return index > -1 ? process.argv[index + 1] : undefined
}

function writeArchive({ path, banner, payload }) {
  const body = `/**\n${banner}\n */\n\nexport default ${JSON.stringify(payload, null, 2)}\n`
  writeFileSync(path, body)
  return body.length
}

async function main() {
  const config = assertConfigured(readEspnEnv(process.env))
  const live = currentSeason()

  console.log(`\n  league  ${config.leagueId}`)
  console.log(`  auth    ${config.hasCredentials ? 'espn_s2 + SWID present' : 'none (public league)'}`)

  let seasons
  const requested = arg('seasons')
  if (requested) {
    seasons = requested.split(',').map((value) => Number(value.trim())).filter(isValidSeason)
  } else {
    // The current season lists the ones before it, and only those are finished.
    const head = await fetchLeagueRaw({
      leagueId: config.leagueId,
      season: live,
      views: LEAGUE_VIEWS,
      espnS2: config.espnS2,
      swid: config.swid,
    })
    seasons = (head?.status?.previousSeasons ?? []).filter(isValidSeason).sort((a, b) => a - b)
  }

  if (!seasons.length) {
    console.error('\n  ✗ No completed seasons to import.\n')
    process.exit(1)
  }

  console.log(`  seasons ${seasons.join(', ')}  (${live} stays live)\n`)

  const done = []
  for (const season of seasons) {
    const started = Date.now()
    try {
      const { trades, pickups, counters, weeksRead } = await loadSeasonActivity({ config, season })
      const faab = trades.filter((trade) => trade.isFaabDeal).length
      const adds = counters.reduce((sum, entry) => sum + entry.adds, 0)
      done.push({ season, trades, pickups, counters })
      console.log(
        `  ✓ ${season}  ${String(trades.length).padStart(3)} trades ` +
          `(${trades.length - faab} scored, ${faab} FAAB)  ` +
          `${String(pickups.length).padStart(3)}/${adds} pickups named  ` +
          `${weeksRead} weeks  ${((Date.now() - started) / 1000).toFixed(1)}s`,
      )
    } catch (error) {
      console.error(`  ✗ ${season}  ${error.message}`)
    }
  }

  if (!done.length) {
    console.error('\n  ✗ Nothing imported.\n')
    process.exit(1)
  }

  const generatedAt = new Date().toISOString()
  const importedSeasons = done.map((entry) => entry.season)
  const trades = done.flatMap((entry) => entry.trades)
  const pickups = done.flatMap((entry) => entry.pickups)
  const counters = done.flatMap((entry) => entry.counters)

  const tradeBytes = writeArchive({
    path: TRADES_OUT,
    banner: ` * Trades for the seasons that are over, precomputed.
 * Generated by scripts/trades/import.mjs — do not edit.
 *
 * Rebuilding these costs a weekly roster read per week of every season; they
 * cannot change now, so /api/trades reads this and fetches only the season
 * being played. See src/lib/trades/build.js for how a trade is reconstructed
 * and why a FAAB deal carries no verdict.`,
    payload: {
      source: 'ESPN rosters + weekly boxscores, via scripts/trades/import.mjs',
      generatedAt,
      seasons: importedSeasons,
      trades,
    },
  })

  const waiverBytes = writeArchive({
    path: WAIVERS_OUT,
    banner: ` * Waiver activity for the seasons that are over, precomputed.
 * Generated by scripts/trades/import.mjs — do not edit.
 *
 * \`counters\` are ESPN's own per-team tallies and are exact. \`pickups\` are
 * reconstructed from the weekly rosters and name about three quarters of them —
 * see src/lib/waivers/build.js for which quarter goes missing and why.`,
    payload: {
      source: 'ESPN transaction counters + weekly rosters, via scripts/trades/import.mjs',
      generatedAt,
      seasons: importedSeasons,
      counters,
      pickups,
    },
  })

  const faab = trades.filter((trade) => trade.isFaabDeal).length
  const adds = counters.reduce((sum, entry) => sum + entry.adds, 0)

  console.log(`\n  → ${TRADES_OUT.replace(ROOT, '.')}  ${(tradeBytes / 1024).toFixed(0)} KB`)
  console.log(`    ${trades.length} trades, ${trades.length - faab} scoreable, ${faab} paid in FAAB`)
  console.log(`  → ${WAIVERS_OUT.replace(ROOT, '.')}  ${(waiverBytes / 1024).toFixed(0)} KB`)
  console.log(`    ${adds} adds counted, ${pickups.length} named (${Math.round((pickups.length / adds) * 100)}%)\n`)
}

main().catch((error) => {
  console.error(`\n  ✗ ${error.message}\n`)
  process.exit(1)
})
